title: Sam Zhu
logo: /asset/img/headshot.jpg

description: Software Developer
email: "sam.zhu992@gmail.com"
phone: 7807086648
location: Edmonton, AB, T6V 1N3

# show_downloads: true
theme: jekyll-theme-minimal
