title: Sam Zhu
# logo: /assets/img/headshot_cicrle.png
# description: text below image
Strengths
Detail Oriented: Demonstrated exceptional attention to detail to ensure high-quality code and stable system performance.

Teamwork: Effectively coordinating with team members to achieve project goals and enhance productivity.

# show_downloads: true
theme: jekyll-theme-minimal
